### PR TITLE
Refine codes

### PR DESCRIPTION
**Pull request by wfystx**
Did little change on Zhe's GossipNode code. 
And now GossipNode is using kvstore instead of directly using leveldb.
Wrote get/put functions for GossipNode.

### CODE REVIEW

**Comment by wfystx** [comment]
BTW. Also created unittest for the functions mentioned above. And cmake for build

**Comment by zhou-1** [comment]
Nice job on these! unit test is really convenient!

**Comment by aktrinh17** [comment]
Looks good, great work!

**Comment by thezhe** [comment]
Looks great!

**Review by thezhe — APPROVED** [review]
Looks great

**Pull request merged**
