### PR TITLE
kv-engine implementation with googletest for unittests 

### PR DESCRIPTION
**Pull request by wfystx**
implemented kv-engine
integrated googletest for unittests (see src/kvstore/test/LevelEngineTest for example)
used cmake for build
enhanced gitignore
added get started section to README

### CODE REVIEW

**Review by zhou-1 — COMMENTED** [review]
Awesome! But shall we use Conan instead of CMake in the future?

**Comment by aktrinh17** [comment]
Looks great

**Comment by wfystx** [comment]
> Awesome! But shall we use Conan instead of CMake in the future?

Idk. What did Anish say?

**Review by 827265717 — COMMENTED** [review]
I remember that Bowen advised us to use conan instead of cmake

**Pull request merged**
