### PR TITLE
Garbage Collection

### PR DESCRIPTION
**Pull request by aktrinh17**
- Implemented garbage collection within the JSON parsing library
- Automatically garbage collects whenever a new log is being added 
- Logs which are at least 10 minutes old are removed from the log file

### CODE REVIEW

**Comment by thezhe** [comment]
Nice work!

**Review by thezhe — APPROVED** [review]
Nice work!

**Review by wfystx — APPROVED** [review]
Great code with good comments. 👍

**Comment by wfystx** [comment]
great work with good comments 👍

**Pull request merged**
